### ISSUE TITLE
failure with TensorOperations.jl v1.3.0

### ISSUE THREAD

**Issue by jfeist** [Jutho/CuTensorOperations.jl#1]
`using CuTensorOperations` fails for me after upgrading TensorOperations.jl to v1.3.0. It tries to import and use `processcontractorder`, which does not seem to exist anymore:
```julia
julia> using CuTensorOperations
[ Info: Precompiling CuTensorOperations [01a401d6-3e09-11e9-13be-6f1bb8674acf]
ERROR: LoadError: UndefVarError: processcontractorder not defined
Stacktrace:
 [1] include at ./boot.jl:326 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1038
 [3] include(::Module, ::String) at ./sysimg.jl:29
 [4] top-level scope at none:2
 [5] eval at ./boot.jl:328 [inlined]
 [6] eval(::Expr) at ./client.jl:404
 [7] top-level scope at ./none:3
in expression starting at /share/apps/julia/julia-1.1.0/share/julia/packages/CuTensorOperations/LqiPN/src/CuTensorOperations.jl:16
ERROR: Failed to precompile CuTensorOperations [01a401d6-3e09-11e9-13be-6f1bb8674acf] to /home/feist/.julia/compiled/v1.1/CuTensorOperations/FJE96.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1197
 [3] _require(::Base.PkgId) at ./loading.jl:960
 [4] require(::Base.PkgId) at ./loading.jl:858
 [5] require(::Module, ::Symbol) at ./loading.jl:853
```

I checked that downgrading to TensorOperations v1.2.0 resolves this.

**Comment by Jutho** [comment]
Oops; sorry about that. My intention was to incorporate CuTensorOperations.jl into TensorOperations.jl with the new parser rewrite; but then I hold off because I noticed that CuArrays.jl still has no new tagged version since the CuTensor support was merged into its master branch, so I could not list it as a requirement. I'll try to fix this for you asap.

**Comment by Jutho** [comment]
Updated the master of this repo; could you check if everything is working again?

**Comment by jfeist** [comment]
It's working now - thanks a lot for the quick fix!

**Comment by Jutho** [comment]
Great to hear; keep me updated in case of any problems. I am not actively using this myself right now. I do plan to merge this into TensorOperations.jl when CuArrays tags a new version.
